version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: dashboard_image
    container_name: dashboard_container
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  database:
    image: mysql:5.7
    container_name: dashboard_db
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dashboard_db_admin
    links:
      - database
    environment:
      PMA_HOST: dashboard_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata: